export const ICONS = [
  "adobe-after-effects", "adobe-illustrator", "adobe-indesign", "adobe-lightroom",
  "adobe-photoshop", "adobe-xd", "align-horizontal-spacing", "align-left-box",
  "align-right-box", "app-notification", "apple-half", "apple-imac2021", "apple-swift",
  "apple", "archery", "arrow-archery", "asana", "at-sign", "bag", "balcony",
  "basketball-field", "basketball", "bathroom", "bbq", "beach-bag", "bell-notification",
  "birthday-cake", "bitcoin-circle", "bluetooth", "bonfire", "book-lock", "book-stack",
  "book", "bookmark-book", "bowling-ball", "boxing-glove", "bread-slice", "bug",
  "building", "card-lock", "cellar", "check-circle", "check-square", "check",
  "chocolate", "church-side", "church", "cinema-old", "city", "clipboard-check",
  "cloud-check", "cloud-desync", "code-brackets-square", "code-brackets", "code",
  "codepen", "coffee-cup", "coins", "cracked-egg", "creative-commons", "css3",
  "cutlery", "cycling", "database-search", "database-settings", "database", "developer",
  "dollar-circle", "double-check", "download-circle", "download", "drag-hand-gesture",
  "droplet-half", "droplet", "egg", "electronics-chip", "electronics-transistor",
  "elevator", "emoji-ball", "emoji-blink-left", "emoji-blink-right", "emoji-look-down",
  "emoji-look-left", "emoji-look-right", "emoji-look-up", "emoji-puzzled", "emoji-quite",
  "emoji-really", "emoji-sad", "emoji-satisfied", "emoji-sing-left-note", "emoji-sing-left",
  "emoji-sing-right-note", "emoji-sing-right", "emoji-surprise-alt", "emoji-surprise",
  "emoji-talking-angry", "emoji-talking-happy", "emoji-think-left", "emoji-think-right",
  "emoji", "erase", "ethereum-circle", "euro-square", "eye-closed", "eye", "farm",
  "favourite-book", "fire-flame", "fish", "fishing", "flip", "flower", "football-ball",
  "football", "garage", "git", "glass-empty", "glass-half-alt", "glass-half", "glasses",
  "golf", "graph-down", "graph-up", "gym", "hand-cash", "handbag", "hat", "headset",
  "heart", "help-square", "hospital", "hourglass", "house-rooms", "html5", "ice-cream",
  "iconoir", "industry", "info-circle", "jellyfish", "kanban-board", "laptop-dev-mode",
  "leaderboard-star", "leaderboard", "map", "math-book", "medal", "medal1st", "menu",
  "mobile-dev-mode", "movie", "music-note", "neighbourhood", "npm-square", "npm",
  "oil-industry", "one-finger-select-hand-gesture", "open-select-hand-gesture",
  "orange-half", "orange-slice-alt", "orange-slice", "palette", "pants-pockets", "pants",
  "peace-hand", "percentage-square", "percentage", "phone-income", "phone-outcome",
  "pizza-slice", "planimetry", "plug-type-a", "plug-type-c", "plug-type-g", "plus-circle",
  "plus-square", "plus", "polar-sh", "presentation", "prohibition", "puzzle",
  "question-mark", "quote", "redo-circle", "refresh-circle", "refresh-double", "refresh",
  "reminder-hand-gesture", "report-columns", "reports", "rings", "running", "sandals",
  "scarf", "sea-and-sun", "sea-waves", "share-android", "shirt-tank-top", "shirt",
  "shop-four-tiles-window", "shop-four-tiles", "shop-window", "shop", "short-pants-pockets",
  "short-pants", "single-tap-gesture", "skateboard", "skateboarding", "slash", "slips",
  "soccer-ball", "spades", "spock-hand-gesture", "suitcase", "swimming", "tennis-ball",
  "trash", "trekking", "trello", "trophy", "tunnel", "umbrella", "undo", "unity",
  "unity5", "upload-square", "upload", "vue-js", "warning-square", "wolf", "xmark-circle",
  "yen-square", "yoga"
];
